In [2]:
from basicblock import pixel_unshuffle, pixel_shuffle
from torch import Tensor

/home/prunet/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [11]:
t = Tensor([[[1,2],[3,4]],[[5,6],[7,8]]])

In [13]:
tt = pixel_shuffle(t,2)

In [14]:
tt.shape

torch.Size([2, 1, 4])

In [15]:
ttt=pixel_unshuffle(tt,2)

In [16]:
ttt

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [17]:
t

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [18]:
tt

tensor([[[1., 3., 2., 4.]],

        [[5., 7., 6., 8.]]])