In [2]:
from basicblock import pixel_unshuffle, pixel_shuffle
from torch import Tensor
import torch

In [3]:
t = Tensor([[[1,2],[3,4]],[[5,6],[7,8]]])

In [4]:
tt = pixel_shuffle(t,2)

In [5]:
tt.shape

torch.Size([2, 1, 4])

In [6]:
ttt=pixel_unshuffle(tt,2)

In [7]:
ttt

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [8]:
t

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [9]:
tt

tensor([[[1., 3., 2., 4.]],

        [[5., 7., 6., 8.]]])

In [10]:
x = torch.rand(1,3,256)

In [ ]:
# GRANDEE must be defined in PYTHONPATH for this to work...
from network_unet import UNetRes
n = UNetRes(in_nc=3, out_nc=3)

In [15]:
with torch.no_grad():
    y = n(x)
y.size()

torch.Size([1, 3, 256])